import Foundation

/// Resolves the Homebrew prefix: `/opt/homebrew` on Apple Silicon, `/usr/local`
/// on Intel. Falls back to `/opt/homebrew` when neither `och` binary is found,
/// so the defaults stay stable and remain overridable via config.toml.
enum BrewPrefix {
    static let path: String = {
        for prefix in ["/opt/homebrew", "/usr/local"] where
            FileManager.default.isExecutableFile(atPath: "\(prefix)/bin/och") {
            return prefix
        }
        return "/opt/homebrew"
    }()
}

struct AppConfig: Equatable {
    var vpnHost = ""
    var vpnUser = ""
    var vpnAuthGroup = ""
    var defaultHost = "och-target"
    var targetHost = ""
    var targetPort = "22"
    var targetUser = NSUserName()
    var extraRoutesText = ""
    var proxyLocalHost = "127.0.0.1"
    var proxyLocalPort = "7890"
    var proxyRemotePort = "7890"
    var ochPath = "\(BrewPrefix.path)/bin/och"
    var ochVpnPath = "\(BrewPrefix.path)/bin/och-vpn"
    var askpassPath = "\(BrewPrefix.path)/libexec/och/och-sudo-askpass.sh"

    var extraRoutes: [String] {
        extraRoutesText
            .split(whereSeparator: { $0 == "\n" || $0 == " " || $0 == "\t" || $0 == "," })
            .map(String.init)
            .filter { !$0.isEmpty }
    }
}

enum ConfigPaths {
    static let configDirectory = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".config/och", isDirectory: true)
    static let configTOML = configDirectory.appendingPathComponent("config.toml")
    static let sshConfig = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".ssh/config")
    static let managedSSHConfig = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".ssh/och.config")
}

enum TOMLConfigError: LocalizedError {
    case invalidLine(Int, String)
    case invalidSection(Int, String)

    var errorDescription: String? {
        switch self {
        case .invalidLine(let line, let value):
            return L10n.tr("error.toml.invalid_line", line, value)
        case .invalidSection(let line, let value):
            return L10n.tr("error.toml.invalid_section", line, value)
        }
    }
}

enum TOMLConfigFile {
    static func load(from url: URL) throws -> AppConfig {
        let contents = try String(contentsOf: url, encoding: .utf8)
        return try parse(contents)
    }

    static func save(_ config: AppConfig, to url: URL) throws {
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        try render(config).write(to: url, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
    }

    static func render(_ config: AppConfig) -> String {
        let routes = config.extraRoutes
            .map { quote($0) }
            .joined(separator: ", ")

        return """
        # Generated by OCH. VPN password is stored in Keychain, not in this file.

        [vpn]
        host = \(quote(config.vpnHost))
        user = \(quote(config.vpnUser))
        auth_group = \(quote(config.vpnAuthGroup))

        [ssh]
        host = \(quote(config.defaultHost))
        target_host = \(quote(config.targetHost))
        user = \(quote(config.targetUser))
        port = \(quote(config.targetPort))

        [routes]
        extra = [\(routes)]

        [proxy]
        local_host = \(quote(config.proxyLocalHost))
        local_port = \(quote(config.proxyLocalPort))
        remote_port = \(quote(config.proxyRemotePort))

        [paths]
        och = \(quote(config.ochPath))
        och_vpn = \(quote(config.ochVpnPath))
        askpass = \(quote(config.askpassPath))

        """
    }

    static func parse(_ contents: String) throws -> AppConfig {
        var config = AppConfig()
        var section = ""
        var routes: [String] = []
        var sawRoutes = false

        for (index, rawLine) in contents.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
            let lineNumber = index + 1
            let withoutComment = stripComment(String(rawLine))
            let line = withoutComment.trimmingCharacters(in: .whitespaces)
            guard !line.isEmpty else {
                continue
            }

            if line.hasPrefix("["), line.hasSuffix("]") {
                let name = String(line.dropFirst().dropLast()).trimmingCharacters(in: .whitespaces)
                guard !name.isEmpty else {
                    throw TOMLConfigError.invalidSection(lineNumber, line)
                }
                section = name
                continue
            }

            let pair = try parsePair(line, lineNumber: lineNumber)
            if section == "routes", pair.key == "extra" {
                routes = try parseArray(pair.value, lineNumber: lineNumber)
                sawRoutes = true
                continue
            }
            apply(pair.value, section: section, key: pair.key, to: &config)
        }

        if sawRoutes {
            config.extraRoutesText = routes.joined(separator: "\n")
        }
        return config
    }

    private static func parsePair(_ line: String, lineNumber: Int) throws -> (key: String, value: String) {
        guard let equals = line.firstIndex(of: "=") else {
            throw TOMLConfigError.invalidLine(lineNumber, line)
        }
        let key = String(line[..<equals]).trimmingCharacters(in: .whitespaces)
        let rawValue = String(line[line.index(after: equals)...]).trimmingCharacters(in: .whitespaces)
        return (key, unquote(rawValue))
    }

    private static func parseArray(_ value: String, lineNumber: Int) throws -> [String] {
        let trimmed = value.trimmingCharacters(in: .whitespaces)
        guard trimmed.hasPrefix("["), trimmed.hasSuffix("]") else {
            throw TOMLConfigError.invalidLine(lineNumber, value)
        }

        let body = String(trimmed.dropFirst().dropLast()).trimmingCharacters(in: .whitespaces)
        guard !body.isEmpty else { return [] }

        return body
            .split(separator: ",")
            .map { unquote($0.trimmingCharacters(in: .whitespaces)) }
            .filter { !$0.isEmpty }
    }

    private static func apply(_ value: String, section: String, key: String, to config: inout AppConfig) {
        switch (section, key) {
        case ("vpn", "host"):
            config.vpnHost = value
        case ("vpn", "user"):
            config.vpnUser = value
        case ("vpn", "auth_group"):
            config.vpnAuthGroup = value
        case ("ssh", "host"):
            config.defaultHost = value
        case ("ssh", "target_host"):
            config.targetHost = value
        case ("ssh", "user"):
            config.targetUser = value
        case ("ssh", "port"):
            config.targetPort = value
        case ("proxy", "local_host"):
            config.proxyLocalHost = value
        case ("proxy", "local_port"):
            config.proxyLocalPort = value
        case ("proxy", "remote_port"):
            config.proxyRemotePort = value
        case ("paths", "och"):
            config.ochPath = value
        case ("paths", "och_vpn"):
            config.ochVpnPath = value
        case ("paths", "askpass"):
            config.askpassPath = value
        default:
            break
        }
    }

    private static func quote(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    private static func unquote(_ value: String) -> String {
        guard value.count >= 2 else { return value }
        if value.hasPrefix("\""), value.hasSuffix("\"") {
            let body = String(value.dropFirst().dropLast())
            return body
                .replacingOccurrences(of: "\\\"", with: "\"")
                .replacingOccurrences(of: "\\\\", with: "\\")
        }
        if value.hasPrefix("'"), value.hasSuffix("'") {
            return String(value.dropFirst().dropLast())
        }
        return value
    }

    private static func stripComment(_ line: String) -> String {
        var result = ""
        var inDoubleQuote = false
        var inSingleQuote = false
        var escaping = false

        for character in line {
            if escaping {
                result.append(character)
                escaping = false
                continue
            }

            if character == "\\" {
                result.append(character)
                escaping = inDoubleQuote
                continue
            }

            if character == "\"", !inSingleQuote {
                inDoubleQuote.toggle()
            } else if character == "'", !inDoubleQuote {
                inSingleQuote.toggle()
            } else if character == "#", !inDoubleQuote, !inSingleQuote {
                break
            }

            result.append(character)
        }

        return result
    }
}
