import Foundation

enum AppRouteMode: String, CaseIterable, Identifiable {
    case openconnect
    case extra

    var id: String { rawValue }

    var titleKey: String {
        switch self {
        case .openconnect:
            return "route_mode.openconnect"
        case .extra:
            return "route_mode.extra"
        }
    }
}

enum AppDNSMode: String, CaseIterable, Identifiable {
    case openconnect
    case ignore

    var id: String { rawValue }

    var titleKey: String {
        switch self {
        case .openconnect:
            return "dns_mode.openconnect"
        case .ignore:
            return "dns_mode.ignore"
        }
    }
}

struct AppConfig: Equatable {
    var vpnHost = ""
    var vpnUser = ""
    var vpnAuthGroup = ""
    var defaultHost = "och-target"
    var targetHost = ""
    var targetPort = "22"
    var targetUser = NSUserName()
    var routeMode: AppRouteMode = .openconnect
    var extraRoutesText = ""
    var dnsMode: AppDNSMode = .openconnect
    var proxyEnabled = false
    var proxyLocalHost = "127.0.0.1"
    var proxyLocalPort = "7890"
    var proxyRemotePort = "7890"
    var appLanguage: AppLanguage = .system

    var extraRoutes: [String] {
        extraRoutesText
            .split(whereSeparator: { $0 == "\n" || $0 == " " || $0 == "\t" || $0 == "," })
            .map(String.init)
            .filter { !$0.isEmpty }
    }

    var hasVPNConfig: Bool {
        !vpnHost.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            && !vpnUser.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }

    var hasManagedSSHConfig: Bool {
        !defaultHost.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            && !targetHost.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            && !targetUser.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
            && !targetPort.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty
    }
}

enum ConfigPaths {
    static let configDirectory = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".config/och", isDirectory: true)
    static let configTOML = configDirectory.appendingPathComponent("config.toml")
    static let sshConfig = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".ssh/config")
    static let managedSSHConfig = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".ssh/och.config")
}

enum TOMLConfigError: LocalizedError {
    case invalidLine(Int, String)
    case invalidSection(Int, String)
    case unknownSection(Int, String)
    case pathsKey(Int, String)
    case unknownKey(Int, String, String)
    case invalidValue(Int, String, String)
    case missingRequired(String)

    var errorDescription: String? {
        localizedDescription(language: .system)
    }

    func localizedDescription(language: AppLanguage) -> String {
        switch self {
        case .invalidLine(let line, let value):
            return L10n.tr("error.toml.invalid_line", language: language, line, value)
        case .invalidSection(let line, let value):
            return L10n.tr("error.toml.invalid_section", language: language, line, value)
        case .unknownSection(let line, let value):
            return L10n.tr("error.toml.unknown_section", language: language, line, value)
        case .pathsKey(let line, let key):
            return L10n.tr("error.toml.paths_key", language: language, key, line)
        case .unknownKey(let line, let section, let key):
            return L10n.tr("error.toml.unknown_key", language: language, line, section, key)
        case .invalidValue(let line, let key, let value):
            return L10n.tr("error.toml.invalid_value", language: language, line, key, value)
        case .missingRequired(let key):
            return L10n.tr("error.toml.missing_required", language: language, key)
        }
    }
}

enum TOMLConfigFile {
    static func load(from url: URL) throws -> AppConfig {
        let contents = try String(contentsOf: url, encoding: .utf8)
        return try parse(contents)
    }

    static func save(_ config: AppConfig, to url: URL) throws {
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        try render(config).write(to: url, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
    }

    static func render(_ config: AppConfig) -> String {
        let routes = config.extraRoutes
            .map { quote($0) }
            .joined(separator: ", ")
        let proxySection = config.proxyEnabled
            ? """

        [proxy]
        local_host = \(quote(config.proxyLocalHost))
        local_port = \(quote(config.proxyLocalPort))
        remote_port = \(quote(config.proxyRemotePort))
        """
            : ""

        return """
        # Generated by OCH. VPN password is stored separately, not in this file.

        [vpn]
        host = \(quote(config.vpnHost))
        user = \(quote(config.vpnUser))
        auth_group = \(quote(config.vpnAuthGroup))

        [ssh]
        host = \(quote(config.defaultHost))
        target_host = \(quote(config.targetHost))
        user = \(quote(config.targetUser))
        port = \(quote(config.targetPort))

        [routes]
        mode = \(quote(config.routeMode.rawValue))
        extra = [\(routes)]

        [dns]
        mode = \(quote(config.dnsMode.rawValue))
        \(proxySection)

        [paths]
        # Runtime helper paths are fixed by the installed app or CLI layout.

        [app]
        language = \(quote(config.appLanguage.rawValue))

        """
    }

    static func parse(_ contents: String) throws -> AppConfig {
        var config = AppConfig()
        var section = ""
        var routes: [String] = []
        var routeMode: AppRouteMode?
        var sawRoutes = false
        var seenKeys = Set<String>()

        for (index, rawLine) in contents.split(separator: "\n", omittingEmptySubsequences: false).enumerated() {
            let lineNumber = index + 1
            let withoutComment = stripComment(String(rawLine))
            let line = withoutComment.trimmingCharacters(in: .whitespaces)
            guard !line.isEmpty else {
                continue
            }

            if line.hasPrefix("["), line.hasSuffix("]") {
                let name = String(line.dropFirst().dropLast()).trimmingCharacters(in: .whitespaces)
                guard !name.isEmpty else {
                    throw TOMLConfigError.invalidSection(lineNumber, line)
                }
                guard allowedSections.contains(name) else {
                    throw TOMLConfigError.unknownSection(lineNumber, name)
                }
                section = name
                if section == "proxy" {
                    config.proxyEnabled = true
                }
                continue
            }

            let pair = try parsePair(line, lineNumber: lineNumber)
            if section == "routes", pair.key == "extra" {
                routes = try parseArray(pair.value, lineNumber: lineNumber)
                sawRoutes = true
                seenKeys.insert("routes.extra")
                continue
            }
            if section == "routes", pair.key == "mode" {
                let value = unquote(pair.value)
                guard let mode = AppRouteMode(rawValue: value) else {
                    throw TOMLConfigError.invalidValue(lineNumber, "routes.mode", value)
                }
                routeMode = mode
                seenKeys.insert("routes.mode")
                continue
            }
            try apply(pair.value, section: section, key: pair.key, lineNumber: lineNumber, to: &config)
            seenKeys.insert("\(section).\(pair.key)")
        }

        if let routeMode {
            config.routeMode = routeMode
        } else if sawRoutes, !routes.isEmpty {
            config.routeMode = .extra
        }
        if sawRoutes {
            config.extraRoutesText = routes.joined(separator: "\n")
        }
        try validateRequiredKeys(seenKeys, config: config)
        return config
    }

    private static func parsePair(_ line: String, lineNumber: Int) throws -> (key: String, value: String) {
        guard let equals = line.firstIndex(of: "=") else {
            throw TOMLConfigError.invalidLine(lineNumber, line)
        }
        let key = String(line[..<equals]).trimmingCharacters(in: .whitespaces)
        let rawValue = String(line[line.index(after: equals)...]).trimmingCharacters(in: .whitespaces)
        return (key, unquote(rawValue))
    }

    private static func parseArray(_ value: String, lineNumber: Int) throws -> [String] {
        let trimmed = value.trimmingCharacters(in: .whitespaces)
        guard trimmed.hasPrefix("["), trimmed.hasSuffix("]") else {
            throw TOMLConfigError.invalidLine(lineNumber, value)
        }

        let body = String(trimmed.dropFirst().dropLast()).trimmingCharacters(in: .whitespaces)
        guard !body.isEmpty else { return [] }

        return body
            .split(separator: ",")
            .map { unquote($0.trimmingCharacters(in: .whitespaces)) }
            .filter { !$0.isEmpty }
    }

    private static let allowedSections = Set(["vpn", "ssh", "routes", "dns", "proxy", "paths", "app"])

    private static let requiredKeys = [
        "vpn.host",
        "vpn.user"
    ]

    private static func apply(
        _ value: String,
        section: String,
        key: String,
        lineNumber: Int,
        to config: inout AppConfig
    ) throws {
        switch (section, key) {
        case ("vpn", "host"):
            config.vpnHost = value
        case ("vpn", "user"):
            config.vpnUser = value
        case ("vpn", "auth_group"):
            config.vpnAuthGroup = value
        case ("ssh", "host"):
            config.defaultHost = value
        case ("ssh", "target_host"):
            config.targetHost = value
        case ("ssh", "user"):
            config.targetUser = value
        case ("ssh", "port"):
            config.targetPort = value
        case ("proxy", "local_host"):
            config.proxyLocalHost = value
        case ("proxy", "local_port"):
            config.proxyLocalPort = value
        case ("proxy", "remote_port"):
            config.proxyRemotePort = value
        case ("dns", "mode"):
            guard let mode = AppDNSMode(rawValue: value) else {
                throw TOMLConfigError.invalidValue(lineNumber, "dns.mode", value)
            }
            config.dnsMode = mode
        case ("app", "language"):
            guard let language = AppLanguage(rawValue: value) else {
                throw TOMLConfigError.invalidValue(lineNumber, "app.language", value)
            }
            config.appLanguage = language
        case ("paths", _):
            throw TOMLConfigError.pathsKey(lineNumber, key)
        default:
            throw TOMLConfigError.unknownKey(lineNumber, section, key)
        }
    }

    private static func validateRequiredKeys(_ seenKeys: Set<String>, config: AppConfig) throws {
        for key in requiredKeys where !seenKeys.contains(key) {
            throw TOMLConfigError.missingRequired(key)
        }
        let requiredValues = [
            ("vpn.host", config.vpnHost),
            ("vpn.user", config.vpnUser)
        ]
        for (key, value) in requiredValues where value.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            throw TOMLConfigError.missingRequired(key)
        }
    }

    private static func quote(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
        return "\"\(escaped)\""
    }

    private static func unquote(_ value: String) -> String {
        guard value.count >= 2 else { return value }
        if value.hasPrefix("\""), value.hasSuffix("\"") {
            let body = String(value.dropFirst().dropLast())
            return body
                .replacingOccurrences(of: "\\\"", with: "\"")
                .replacingOccurrences(of: "\\\\", with: "\\")
        }
        if value.hasPrefix("'"), value.hasSuffix("'") {
            return String(value.dropFirst().dropLast())
        }
        return value
    }

    private static func stripComment(_ line: String) -> String {
        var result = ""
        var inDoubleQuote = false
        var inSingleQuote = false
        var escaping = false

        for character in line {
            if escaping {
                result.append(character)
                escaping = false
                continue
            }

            if character == "\\" {
                result.append(character)
                escaping = inDoubleQuote
                continue
            }

            if character == "\"", !inSingleQuote {
                inDoubleQuote.toggle()
            } else if character == "'", !inDoubleQuote {
                inSingleQuote.toggle()
            } else if character == "#", !inDoubleQuote, !inSingleQuote {
                break
            }

            result.append(character)
        }

        return result
    }
}
