import Foundation

/// Resolves the Homebrew prefix: `/opt/homebrew` on Apple Silicon, `/usr/local`
/// on Intel. Falls back to `/opt/homebrew` when neither `och` binary is found,
/// so the defaults stay stable and remain overridable via gui.env.
enum BrewPrefix {
    static let path: String = {
        for prefix in ["/opt/homebrew", "/usr/local"] where
            FileManager.default.isExecutableFile(atPath: "\(prefix)/bin/och") {
            return prefix
        }
        return "/opt/homebrew"
    }()
}

struct AppConfig: Equatable {
    var vpnHost = ""
    var vpnUser = ""
    var vpnAuthGroup = ""
    var defaultHost = "och-target"
    var targetHost = ""
    var targetPort = "22"
    var targetUser = NSUserName()
    var extraRoutesText = ""
    var proxyLocalHost = "127.0.0.1"
    var proxyLocalPort = "7890"
    var proxyRemotePort = "7890"
    var ochPath = "\(BrewPrefix.path)/bin/och"
    var ochVpnPath = "\(BrewPrefix.path)/bin/och-vpn"
    var askpassPath = "\(BrewPrefix.path)/libexec/och/och-sudo-askpass.sh"

    var extraRoutes: [String] {
        extraRoutesText
            .split(whereSeparator: { $0 == "\n" || $0 == " " || $0 == "\t" || $0 == "," })
            .map(String.init)
            .filter { !$0.isEmpty }
    }
}

enum ConfigPaths {
    static let configDirectory = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".config/och", isDirectory: true)
    static let guiEnv = configDirectory.appendingPathComponent("gui.env")
    static let sshConfig = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".ssh/config")
    static let managedSSHConfig = FileManager.default.homeDirectoryForCurrentUser
        .appendingPathComponent(".ssh/och.config")
}

enum EnvFile {
    static func load(from url: URL) throws -> AppConfig {
        var config = AppConfig()
        guard FileManager.default.fileExists(atPath: url.path) else {
            return config
        }

        let contents = try String(contentsOf: url, encoding: .utf8)
        let values = parse(contents)
        config.vpnHost = values["VPN_HOST"] ?? config.vpnHost
        config.vpnUser = values["VPN_USER"] ?? config.vpnUser
        config.vpnAuthGroup = values["VPN_AUTHGROUP"] ?? config.vpnAuthGroup
        config.defaultHost = values["DEFAULT_HOST"] ?? config.defaultHost
        config.targetHost = values["TARGET_HOST"] ?? config.targetHost
        config.targetPort = values["TARGET_PORT"] ?? config.targetPort
        config.targetUser = values["TARGET_SSH_USER"] ?? config.targetUser
        config.extraRoutesText = (values["MACOS_EXTRA_ROUTES"] ?? "").replacingOccurrences(of: " ", with: "\n")
        config.proxyLocalHost = values["PROXY_LOCAL_HOST"] ?? config.proxyLocalHost
        config.proxyLocalPort = values["PROXY_LOCAL_PORT"] ?? config.proxyLocalPort
        config.proxyRemotePort = values["PROXY_REMOTE_PORT"] ?? config.proxyRemotePort
        config.ochPath = values["OCH_PATH"] ?? config.ochPath
        config.ochVpnPath = values["OCH_VPN_PATH"] ?? config.ochVpnPath
        config.askpassPath = values["OCH_ASKPASS_PATH"] ?? config.askpassPath
        return config
    }

    static func save(_ config: AppConfig, to url: URL) throws {
        try FileManager.default.createDirectory(
            at: url.deletingLastPathComponent(),
            withIntermediateDirectories: true
        )

        let lines = [
            "# Generated by OCH. VPN_PASSWORD is stored in Keychain, not in this file.",
            "VPN_HOST=\(quote(config.vpnHost))",
            "VPN_USER=\(quote(config.vpnUser))",
            config.vpnAuthGroup.isEmpty ? nil : "VPN_AUTHGROUP=\(quote(config.vpnAuthGroup))",
            "DEFAULT_HOST=\(quote(config.defaultHost))",
            "TARGET_HOST=\(quote(config.targetHost))",
            "TARGET_PORT=\(quote(config.targetPort))",
            "TARGET_SSH_USER=\(quote(config.targetUser))",
            config.extraRoutes.isEmpty ? nil : "MACOS_EXTRA_ROUTES=\(quote(config.extraRoutes.joined(separator: " ")))",
            "PROXY_LOCAL_HOST=\(quote(config.proxyLocalHost))",
            "PROXY_LOCAL_PORT=\(quote(config.proxyLocalPort))",
            "PROXY_REMOTE_PORT=\(quote(config.proxyRemotePort))",
            "OCH_PATH=\(quote(config.ochPath))",
            "OCH_VPN_PATH=\(quote(config.ochVpnPath))",
            "OCH_ASKPASS_PATH=\(quote(config.askpassPath))"
        ].compactMap { $0 }.joined(separator: "\n") + "\n"

        try lines.write(to: url, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: url.path)
    }

    private static func parse(_ contents: String) -> [String: String] {
        var result: [String: String] = [:]
        for rawLine in contents.split(separator: "\n", omittingEmptySubsequences: false) {
            let line = rawLine.trimmingCharacters(in: .whitespaces)
            guard !line.isEmpty, !line.hasPrefix("#"), let equals = line.firstIndex(of: "=") else {
                continue
            }
            let key = String(line[..<equals]).trimmingCharacters(in: .whitespaces)
            var value = String(line[line.index(after: equals)...]).trimmingCharacters(in: .whitespaces)
            if value.hasPrefix("\""), value.hasSuffix("\""), value.count >= 2 {
                value.removeFirst()
                value.removeLast()
            }
            result[key] = value
        }
        return result
    }

    private static func quote(_ value: String) -> String {
        let escaped = value
            .replacingOccurrences(of: "\\", with: "\\\\")
            .replacingOccurrences(of: "\"", with: "\\\"")
            .replacingOccurrences(of: "$", with: "\\$")
            .replacingOccurrences(of: "`", with: "\\`")
        return "\"\(escaped)\""
    }
}
