import Foundation

enum SSHConfigManager {
    static let includeLine = "Include ~/.ssh/och.config"

    static func mainConfigIncludesManagedFile() -> Bool {
        guard let contents = try? String(contentsOf: ConfigPaths.sshConfig, encoding: .utf8) else {
            return false
        }
        return contents
            .split(separator: "\n")
            .map { $0.trimmingCharacters(in: .whitespaces) }
            .contains(includeLine)
    }

    static func ensureIncludeLine() throws {
        let sshDir = ConfigPaths.sshConfig.deletingLastPathComponent()
        try FileManager.default.createDirectory(at: sshDir, withIntermediateDirectories: true)

        var contents = ""
        if FileManager.default.fileExists(atPath: ConfigPaths.sshConfig.path) {
            contents = try String(contentsOf: ConfigPaths.sshConfig, encoding: .utf8)
        }

        guard !mainConfigIncludesManagedFile() else {
            return
        }

        if !contents.isEmpty, !contents.hasSuffix("\n") {
            contents += "\n"
        }
        contents += "\(includeLine)\n"
        try contents.write(to: ConfigPaths.sshConfig, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: ConfigPaths.sshConfig.path)
    }

    static func writeManagedHost(config: AppConfig) throws {
        let sshDir = ConfigPaths.managedSSHConfig.deletingLastPathComponent()
        try FileManager.default.createDirectory(at: sshDir, withIntermediateDirectories: true)

        let contents = """
        # Generated by OCH. Edit this file from the OCH app.
        Host \(config.defaultHost)
          HostName \(config.targetHost)
          User \(config.targetUser)
          Port \(config.targetPort)
          ProxyCommand \(config.ochPath) --proxy-command %h %p
          ServerAliveInterval 30
          ServerAliveCountMax 3

        """

        try contents.write(to: ConfigPaths.managedSSHConfig, atomically: true, encoding: .utf8)
        try FileManager.default.setAttributes([.posixPermissions: 0o600], ofItemAtPath: ConfigPaths.managedSSHConfig.path)
    }
}
